version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      

  db:
    image: "redis:alpine"
    ports:
      - "6379:6379"